import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { Badge } from "../components/Badge";
import { DataTable, type Column } from "../components/DataTable";
import { EmptyState } from "../components/EmptyState";
import { StatCard } from "../components/StatCard";
import { useAppData } from "../context/AppDataContext";
import { loanService } from "../services/loanService";
import type { EMISchedule } from "../types";
import { formatCurrency } from "../utils/format";

export default function LoanDetailsPage() {
  const { id = "" } = useParams();
  const { loans } = useAppData();
  const [schedule, setSchedule] = useState<EMISchedule[]>([]);
  const loan = loans.find((item) => item.id === id);
  useEffect(() => {
    void loanService.schedule(id).then(setSchedule);
  }, [id]);
  if (!loan) return <EmptyState title="Loan not found" />;
  const columns: Column<EMISchedule>[] = [
    { key: "installment", header: "Installment #", render: (row) => row.installment },
    { key: "dueDate", header: "Due Date", render: (row) => row.dueDate },
    { key: "due", header: "Due Amount", render: (row) => formatCurrency(row.dueAmount) },
    { key: "paid", header: "Paid", render: (row) => formatCurrency(row.paid) },
    { key: "balance", header: "Balance", render: (row) => formatCurrency(row.balance) },
    { key: "status", header: "Status", render: (row) => <Badge>{row.status}</Badge> },
  ];
  return (
    <div className="grid gap-6">
      <div><h1 className="text-2xl font-black text-slate-950">Loan Details</h1><p className="text-sm font-semibold text-slate-500">{loan.id} · {loan.customerName}</p></div>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard title="Loan Amount" value={formatCurrency(loan.amount)} detail={`${loan.interestRate}% ${loan.interestType}`} icon={null} />
        <StatCard title="Total Payable" value={formatCurrency(loan.totalPayable)} detail={`EMI ${formatCurrency(loan.emi)}`} icon={null} />
        <StatCard title="Paid" value={formatCurrency(loan.paid)} detail={`Frequency ${loan.frequency}`} icon={null} />
        <StatCard title="Outstanding" value={formatCurrency(loan.outstanding)} detail={`Next due ${loan.nextDueDate}`} icon={null} />
      </div>
      <section className="rounded-lg border border-sky-100 bg-white p-5 shadow-sm">
        <div className="grid gap-3 text-sm text-slate-700 md:grid-cols-3">
          <p><strong>Loan Date:</strong> {loan.loanDate}</p>
          <p><strong>First Due Date:</strong> {loan.firstDueDate}</p>
          <p><strong>Status:</strong> <Badge>{loan.status}</Badge></p>
        </div>
      </section>
      <div><h2 className="mb-3 text-lg font-black text-slate-900">EMI Schedule</h2><DataTable columns={columns} data={schedule} empty="Schedule will be generated by backend in Phase 2 for new demo loans." /></div>
    </div>
  );
}
